// AI Phone Agent & Webhook Types
// Supports multiple sources: phone calls, web forms, email, SMS, etc.

// Source types for incoming data
export type IncomingSource = "phone_call" | "web_form" | "email" | "sms" | "chat" | "unknown";

// Incoming webhook raw data (can be any format)
export interface RawWebhookData {
  [key: string]: unknown;
}

// Contact information extracted from any source
export interface ContactInfo {
  name?: string;
  firstName?: string;
  lastName?: string;
  phone?: string;
  email?: string;
  company?: string;
}

// Phone line/user info from GoTo Connect (the internal employee who handled the call)
export interface LineUserInfo {
  name?: string;
  number?: string;
  extension?: string;
  userId?: string;
  type?: string; // e.g., "USER", "QUEUE", "EXTENSION"
}

// Parsed call/interaction record (renamed from CallRecord to support all sources)
export interface CallRecord {
  id: string;

  // Source identification
  source: IncomingSource;
  sourceProvider?: string; // e.g., "vapi", "twilio", "typeform", "jotform"

  // Caller/Contact information (external party)
  callerPhone: string;
  callerName?: string;
  callerEmail?: string;
  contact?: ContactInfo;

  // Internal line/user who handled the call
  lineUser?: LineUserInfo;

  // Call metadata (for phone_call source)
  callStartedAt: Date;
  callEndedAt?: Date;
  durationSeconds: number;
  direction: "inbound" | "outbound";

  // Recording and transcript (for phone_call source)
  recordingUrl?: string;
  transcript?: string;
  transcriptSegments?: TranscriptSegment[];

  // Form data (for web_form source)
  formData?: {
    formName?: string;
    submittedAt?: Date;
    fields: Record<string, unknown>;
  };

  // AI Analysis
  aiAnalysis?: CallAIAnalysis;

  // Client matching
  matchedClientId?: string;
  matchedClientName?: string;
  addedToClientRecord: boolean;

  // Status and assignment
  status: CallStatus;
  assignedTo?: string;
  assignedToName?: string;

  // Tracking
  createdAt: Date;
  updatedAt: Date;
  reviewedAt?: Date;
  reviewedBy?: string;

  // Notes and follow-up
  notes?: string;
  followUpDate?: Date;

  // Raw webhook data for reference
  rawData?: RawWebhookData;

  // AI parsing confidence
  aiConfidence?: number;
}

export interface TranscriptSegment {
  speaker: "agent" | "caller";
  text: string;
  startTime: number;
  endTime: number;
}

export interface CallAIAnalysis {
  // Summary
  summary: string;
  keyPoints: string[];

  // Classification
  category: CallCategory;
  sentiment: "positive" | "neutral" | "negative" | "frustrated";
  urgency: "low" | "medium" | "high" | "urgent";

  // Extracted information
  extractedInfo: {
    reason?: string;
    requestedServices?: string[];
    mentionedDates?: string[];
    mentionedAmounts?: string[];
    questions?: string[];
    concerns?: string[];
  };

  // AI-suggested actions
  suggestedActions: SuggestedCallAction[];

  // Confidence
  confidence: number;
  analyzedAt: Date;
}

export type CallCategory =
  | "new_client_inquiry"
  | "existing_client_question"
  | "document_request"
  | "appointment_scheduling"
  | "payment_inquiry"
  | "tax_question"
  | "status_check"
  | "complaint"
  | "urgent_matter"
  | "follow_up"
  | "voicemail"
  | "wrong_number"
  | "spam"
  | "web_form"
  | "contact_request"
  | "general_inquiry"
  | "other";

export type CallStatus =
  | "new"
  | "in_review"
  | "action_required"
  | "waiting_on_client"
  | "follow_up_scheduled"
  | "completed"
  | "archived";

export interface SuggestedCallAction {
  id: string;
  type: CallActionType;
  label: string;
  description: string;
  priority: "low" | "medium" | "high";
  autoGenerated: boolean;
  // User feedback on AI suggestion
  userFeedback?: "approved" | "rejected" | null;
  feedbackAt?: Date;
}

export type CallActionType =
  | "call_back"
  | "send_email"
  | "send_sms"
  | "create_task"
  | "schedule_appointment"
  | "request_documents"
  | "send_documents"
  | "add_to_client"
  | "assign_to_user"
  | "set_follow_up"
  | "archive"
  | "mark_spam"
  | "custom";

// Custom action rules (like email rules)
export interface CallActionRule {
  id: string;
  name: string;
  isEnabled: boolean;
  priority: number;

  // Conditions
  conditions: CallRuleCondition[];
  conditionOperator: "and" | "or";

  // Actions to take
  actions: CallRuleAction[];

  // Metadata
  createdAt: Date;
  createdBy: string;
  updatedAt: Date;
}

export interface CallRuleCondition {
  field: "category" | "sentiment" | "urgency" | "caller_phone" | "transcript" | "duration";
  operator: "equals" | "contains" | "starts_with" | "ends_with" | "greater_than" | "less_than" | "matches_regex";
  value: string;
  caseSensitive?: boolean;
}

export interface CallRuleAction {
  type: CallActionType;
  value?: string;
  metadata?: Record<string, unknown>;
}

// Notification for new calls
export interface CallNotification {
  id: string;
  callId: string;
  title: string;
  message: string;
  callerName?: string;
  callerPhone: string;
  category: CallCategory;
  urgency: "low" | "medium" | "high" | "urgent";
  createdAt: Date;
  read: boolean;
  dismissed: boolean;
}

// Category display info
export const callCategoryInfo: Record<CallCategory, { label: string; color: string; icon: string }> = {
  new_client_inquiry: { label: "New Client", color: "bg-emerald-100 text-emerald-700", icon: "UserPlus" },
  existing_client_question: { label: "Client Question", color: "bg-blue-100 text-blue-700", icon: "HelpCircle" },
  document_request: { label: "Document Request", color: "bg-purple-100 text-purple-700", icon: "FileText" },
  appointment_scheduling: { label: "Scheduling", color: "bg-orange-100 text-orange-700", icon: "Calendar" },
  payment_inquiry: { label: "Payment", color: "bg-green-100 text-green-700", icon: "DollarSign" },
  tax_question: { label: "Tax Question", color: "bg-indigo-100 text-indigo-700", icon: "Calculator" },
  status_check: { label: "Status Check", color: "bg-cyan-100 text-cyan-700", icon: "Search" },
  complaint: { label: "Complaint", color: "bg-red-100 text-red-700", icon: "AlertTriangle" },
  urgent_matter: { label: "Urgent", color: "bg-red-100 text-red-700", icon: "AlertCircle" },
  follow_up: { label: "Follow Up", color: "bg-amber-100 text-amber-700", icon: "Clock" },
  voicemail: { label: "Voicemail", color: "bg-slate-100 text-slate-700", icon: "Voicemail" },
  wrong_number: { label: "Wrong Number", color: "bg-gray-100 text-gray-500", icon: "PhoneOff" },
  spam: { label: "Spam", color: "bg-gray-100 text-gray-500", icon: "Ban" },
  web_form: { label: "Web Form", color: "bg-teal-100 text-teal-700", icon: "FormInput" },
  contact_request: { label: "Contact Request", color: "bg-sky-100 text-sky-700", icon: "Mail" },
  general_inquiry: { label: "General Inquiry", color: "bg-violet-100 text-violet-700", icon: "MessageSquare" },
  other: { label: "Other", color: "bg-slate-100 text-slate-600", icon: "Phone" },
};

// Source type display info
export const sourceTypeInfo: Record<IncomingSource, { label: string; color: string; icon: string }> = {
  phone_call: { label: "Phone Call", color: "bg-blue-100 text-blue-700", icon: "Phone" },
  web_form: { label: "Web Form", color: "bg-teal-100 text-teal-700", icon: "FormInput" },
  email: { label: "Email", color: "bg-amber-100 text-amber-700", icon: "Mail" },
  sms: { label: "SMS", color: "bg-green-100 text-green-700", icon: "MessageSquare" },
  chat: { label: "Chat", color: "bg-violet-100 text-violet-700", icon: "MessageCircle" },
  unknown: { label: "Unknown", color: "bg-gray-100 text-gray-500", icon: "HelpCircle" },
};

export const callStatusInfo: Record<CallStatus, { label: string; color: string }> = {
  new: { label: "New", color: "bg-blue-500 text-white" },
  in_review: { label: "In Review", color: "bg-violet-500 text-white" },
  action_required: { label: "Action Required", color: "bg-orange-500 text-white" },
  waiting_on_client: { label: "Waiting on Client", color: "bg-amber-500 text-white" },
  follow_up_scheduled: { label: "Follow-up Scheduled", color: "bg-cyan-500 text-white" },
  completed: { label: "Completed", color: "bg-emerald-500 text-white" },
  archived: { label: "Archived", color: "bg-gray-400 text-white" },
};

export const urgencyInfo: Record<string, { label: string; color: string }> = {
  urgent: { label: "Urgent", color: "bg-red-500 text-white" },
  high: { label: "High", color: "bg-orange-500 text-white" },
  medium: { label: "Medium", color: "bg-amber-500 text-white" },
  low: { label: "Low", color: "bg-slate-400 text-white" },
};
